name: LaTeX CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the document in container
      run: |
        docker run \
        -v ${{ github.workspace }}:/data \
        --entrypoint latexmk \
        yipengsun/umd_phd_candidacy_paper:latest
